# Generated by Django 4.2.4 on 2023-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_adminplus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='open_subscriptions',
        ),
    ]
